AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Vigor app
Parameters:
  Stage:
    Type: String
    Default: dev
#Conditions:
#  notDev: !Or
#  - !Equals [ !Ref Stage, "prod" ]
#  - !Equals [ !Ref Stage, "staging" ]
Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt 'GraphQLAPI.ApiId'
      DefinitionS3Location: schema.graphql
  GraphQLAPI:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub vigor-backend-${Stage}
      AuthenticationType: API_KEY
      AdditionalAuthenticationProviders:
      - AuthenticationType: AMAZON_COGNITO_USER_POOLS
        UserPoolConfig:
          AwsRegion: us-east-2
          UserPoolId: us-east-2_NvvTEjnBZ
      LogConfig:
        CloudWatchLogsRoleArn: !GetAtt AppSyncLoggingRole.Arn
        FieldLogLevel: ALL
  CustomActionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: Id
        AttributeType: S
      - AttributeName: Category
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: Id
        KeyType: HASH
      SSESpecification:
        SSEEnabled: true
      TimeToLiveSpecification:
        AttributeName: ExpiryEpoch
        Enabled: true
      GlobalSecondaryIndexes:
      - IndexName: ByCategory
        KeySchema:
        - AttributeName: Category
          KeyType: HASH
        - AttributeName: Id
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
  BoredActionDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      Name: BoredAction
      Type: AWS_LAMBDA
      ServiceRoleArn: !GetAtt AppSyncApiRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt BoredSingle.Arn
  CustomActionsDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      Name: CustomActions
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncApiRole.Arn
      DynamoDBConfig:
        AwsRegion: !Ref 'AWS::Region'
        TableName: !Ref CustomActionTable
  GetBoredActionResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: [GraphQLSchema]
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      DataSourceName: !GetAtt BoredActionDataSource.Name
      FieldName: getBoredAction
      TypeName: Query
      RequestMappingTemplateS3Location: mappings/bored.get.request.vtl
      ResponseMappingTemplateS3Location: mappings/passthrough.response.vtl
  GetActionResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: [GraphQLSchema]
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      DataSourceName: !GetAtt CustomActionsDataSource.Name
      FieldName: getActions
      TypeName: Query
      RequestMappingTemplateS3Location: mappings/action.get.request.vtl
      ResponseMappingTemplateS3Location: mappings/passthrough.response.vtl
  ListCustomActionsResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: [GraphQLSchema]
    Properties:
      ApiId: !GetAtt GraphQLAPI.ApiId
      DataSourceName: !GetAtt CustomActionsDataSource.Name
      FieldName: listCustomActions
      TypeName: Query
      RequestMappingTemplateS3Location: mappings/customActions.list.request.vtl
      ResponseMappingTemplateS3Location: mappings/passthrough.response.vtl
  AppSyncLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Path: /vigor/
      Policies:
        - PolicyName: LogToCW
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - logs:DescribeLogStreams
                Resource: '*'
  AppSyncApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Path: /vigor/
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource:
                  - !GetAtt CustomActionTable.Arn
                  - !Sub '${CustomActionTable.Arn}/*'
        - PolicyName: LambdaAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: '*'
  BoredSingle:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./functions
      Handler: bored.handler
      Runtime: python3.7










Outputs:
  AppSyncApiId:
    Value: !GetAtt GraphQLAPI.ApiId
  AppSyncApiUrl:
    Value: !GetAtt GraphQLAPI.GraphQLUrl
  BucketSite:
    Value: !Join
    - '.'
    - - !Ref StaticSiteBucket
      - !FindInMap [RegionMap, !Ref "AWS::Region", websiteendpoint]
Mappings:
  RegionMap:
    ap-northeast-1:
      S3hostedzoneID: "Z2M4EHUR26P7ZW"
      websiteendpoint: "s3-website-ap-northeast-1.amazonaws.com"
    ap-northeast-2:
      S3hostedzoneID: "Z3W03O7B5YMIYP"
      websiteendpoint: "s3-website.ap-northeast-2.amazonaws.com"
    ap-south-1:
      S3hostedzoneID: "Z11RGJOFQNVJUP"
      websiteendpoint: "s3-website.ap-south-1.amazonaws.com"
    ap-southeast-1:
      S3hostedzoneID: "Z3O0J2DXBE1FTB"
      websiteendpoint: "s3-website-ap-southeast-1.amazonaws.com"
    ap-southeast-2:
      S3hostedzoneID: "Z1WCIGYICN2BYD"
      websiteendpoint: "s3-website-ap-southeast-2.amazonaws.com"
    eu-central-1:
      S3hostedzoneID: "Z21DNDUVLTQW6Q"
      websiteendpoint: "s3-website.eu-central-1.amazonaws.com"
    eu-west-1:
      S3hostedzoneID: "Z1BKCTXD74EZPE"
      websiteendpoint: "s3-website-eu-west-1.amazonaws.com"
    sa-east-1:
      S3hostedzoneID: "Z7KQH4QJS55SO"
      websiteendpoint: "s3-website-sa-east-1.amazonaws.com"
    us-east-1:
      S3hostedzoneID: "Z3AQBSTGFYJSTF"
      websiteendpoint: "s3-website-us-east-1.amazonaws.com"
    us-east-2:
      S3hostedzoneID: "Z2O1EMRO9K5GLX"
      websiteendpoint: "s3-website.us-east-2.amazonaws.com"
    us-west-1:
      S3hostedzoneID: "Z2F56UZL2M1ACD"
      websiteendpoint: "s3-website-us-west-1.amazonaws.com"
    us-west-2:
      S3hostedzoneID: "Z3BJ6K6RIION7M"
      websiteendpoint: "s3-website-us-west-2.amazonaws.com"
